### ISSUE TITLE
Request / Merge feature to the main application

### ISSUE THREAD

**Issue by danielnc** [balvig/chili#14]
Is there any easy way to move a "test" feature to the main application code or we need to manually add it?

I'm afraid deface will slow our app as we keep adding new features

How do you feel about it? do you have any benchmarks?

**Comment by balvig** [comment]
Have no benchmarks I'm afraid... :sweat: but yeh once a feature is "validated" I would personally prefer moving it to the main code, not just for performance's sake but also just to keep "experimental features" and "core functionality" in their right places! :cake: 

Unfortunately it's a bit of a manual process at the moment, depending on the feature you should more or less be able to just copy things over, but you will probably need to make some adjustments, for example un-namespace some things etc :smile:

**Comment by danielnc** [comment]
thx :)
