### ISSUE TITLE
How back the changes to the main app?

### ISSUE THREAD

**Issue by krlsdu** [balvig/chili#15]
In tutorial the changes and modify, extending the code and create some files (migrate) with options false, at this point is ok!
With the code passed in test and have ok to push in env production, how add or merge this new feature to the main code and commit in master branch and submit!

**Comment by balvig** [comment]
@krlsdu that is unfortunately a bit of a manual process at the moment!  :sweat_smile: 

You can either let the code live in the chili feature with `active_if` set to true, or manually copy over the things you need.

**Comment by krlsdu** [comment]
@balvig thanks the answer!
